name: Unit Tests workflow

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Jest tests
    defaults:
      run:
        working-directory: ./www
    steps:
      - uses: actions/checkout@v2
      - name: ğŸ— Install modules
        run: npm install
      - name: ğŸ’» Run tests and collect coverage
        run: npm run test && npm run e2e
      - name: âœ… Upload coverage reports to Codecov with GitHub Action
        uses: codecov/codecov-action@v3
